* topics
** livetemplates
** surround with
** git gutter
** quickfix
** paraminfo
** regex help
** quick docu
** expand selection
** hippie complete
https://www.jetbrains.com/help/webstorm/auto-completing-code.html

* Icon / Symbol reference
https://www.jetbrains.com/help/idea/symbols.html

* Switching files
| shortcut     | description                          |
|--------------+--------------------------------------|
| <ctrl>-<tab> | switcher (most recenntly used files) |

* Navigate
| shortcut | description                     |
|----------+---------------------------------|
| Ö        | File Structure (type to filter) |

** search everywhere
Files, symbols, functions, variables, classes or (IDE) actions
Camel case search works here.

| shortcut                                 | description       |
|------------------------------------------+-------------------|
| <shift><shift>                           | search everywhere |
| <alt> <cursor-up>/<cursor-down>          | history up/down   |
| <alt> <cmd> <cursor-left>/<cursor-right> | next/prev tab     |


* TODO

| shortcut      | description             |
|---------------+-------------------------|
| <alt>-<space> | Quick Definition Viewer |

* Refactoring
** Inline Variable refactoring
** Introduce Variable refactoring

* Completion
When using Code Completion, you can accept the currently highlighted
selection in the popup list with the period character (.), comma (,),
semicolon (;), space and other characters.
The selected name is automatically entered in the editor followed by the entered character.

** Completion in Find Bar
When you are finding text in the current file (⌘F), you don't need to
type the whole search string: Basic Code Completion is available in
the search field. Start typing, press ⌃Space, and select the desired
string from the suggestion list.

** Camel prefixes in code completion/navigation popups
When in the Code Completion lookup, you can ease the search by
filtering the list with the help of the "camel words" prefixes.


* Quick Documentation in lookups
The shortcuts such as F1 (View | Quick Documentation), ⌘P (View | Parameter Info), ⌘B (Navigate | Declaration) and others can be used not only in the editor but in the code completion popup list as well.

* Recent changes
Use ⌥⇧C to quickly review your recent changes to the project.

* Recent files popup
⌘E (View | Recent Files) brings a popup list of the recently visited files. Choose the desired file and press Enter to open it.

* Recent searches history
When searching for a text string in a file, use recent history: with the search pane already open, press ⌘F once again to show the list of recent entries.

* Show usages
You can bring forward the list of all usages of a class, method or variable across the whole project, and quickly jump to the selected usage. To do that, place the caret at the symbol's name or at its usage in code and press ⌥⌘F7 (Edit | Find | Show Usages in the main menu), scroll the list and click the desired usage.

* Surround
** Surround expression/statement with
To quickly wrap a code block in useful constructs, select it in the editor, press ⌥⌘T (Code | Surround With) and choose the desired code block, e.g. if.
The list of available options ("wrappers") is context-sensitive and depends on the language that you are currently using. For example, you can surround html blocks with tags, etc.
** Surround quote, parentheses...
" with active selection will wrap the selection in ""

* Tag Name Completion
A special variant of the Code Completion feature invoked by pressing ⌃Space twice allows you to complete XML tag names from namespaces not declared in the current file. If the namespace is not declared yet the declaration is generated automatically.


move line
